name: Component Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

permissions:
  contents: read

jobs:
  test-services:
    name: Test Services
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run services tests
        run: node --max-old-space-size=4096 node_modules/vitest/vitest.mjs --run src/test/services/**/*.test.ts

  test-hooks:
    name: Test Hooks
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run hooks tests
        run: node --max-old-space-size=4096 node_modules/vitest/vitest.mjs --run src/test/hooks/**/*.test.tsx

  test-components:
    name: Test Components
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run component tests
        run: node --max-old-space-size=4096 node_modules/vitest/vitest.mjs --run src/test/components/**/*.test.tsx

  test-pages:
    name: Test Pages
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run pages tests
        run: node --max-old-space-size=4096 node_modules/vitest/vitest.mjs --run src/test/pages/**/*.test.tsx

  test-app:
    name: Test App
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run app tests
        run: node --max-old-space-size=4096 node_modules/vitest/vitest.mjs --run src/test/App.test.tsx 